config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users

  root to: "aircrafts#index"

  resources :aircrafts do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create]

    collection do
      get :my_aircraft
    end
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: %i[update edit destroy show index] do
    member do
      get :accept
      get :decline
    end
  end
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  validates :title, presence: true
  validates :price_per_day, presence: true
  validates :departure_address, presence: true
  validates :arrival_address, presence: true

  aircraft_search_weighting = {
    aircraft_type: 'A',
    title:'B',
    description: 'C',
    departure_address: 'A',
    arrival_address: 'A'
  }
  pg_search_scope :search_for_aircrafts_type_title_description,
    against: aircraft_search_weighting,
    using:{
     tsearch: { prefix: true }
    }
  scope :price_0_to_500, -> {
    where(price_per_day: (0..500))
  }
  scope :price_500_to_1000, -> {
    where(price_per_day: (500..1000))
  }
  scope :price_over_1000, -> {
      where(price_per_day: (1000..100000))
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, presence: true, comparison: { less_than_or_equal_to: :end_date }
  validates :end_date, presence: true
  validate :start_date_cannot_be_in_the_past, :bookings_must_not_overlap

  belongs_to :aircraft
  belongs_to :user

  def start_date_cannot_be_in_the_past
    if (start_date.present? && start_date < Date.today)
      errors.add(:start_date, "can't be in the past")
    end
  end

  def bookings_must_not_overlap
    return if self
                .class
                .where.not(id: id)
                .where(aircraft_id: aircraft_id)
                .where('start_date < ? AND end_date > ?', end_date, start_date)
                .none?

    errors.add(:start_date, 'Overlapping reservation exists')
    errors.add(:end_date, 'Overlapping reservation exists')
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :aircraft
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :aircrafts, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  before_action :set_aircraft, only: %i[destroy show edit]

  def index
    if params[:query].present?
      @aircrafts = Aircraft.search_for_aircrafts_type_title_description(params[:query])
    elsif params[:price_0_to_500] == "1"
      @aircrafts = Aircraft.price_0_to_500
    elsif params[:price_500_to_1000] == "1"
      @aircrafts = Aircraft.price_500_to_1000
    elsif params[:price_over_1000] == "1"
      @aircrafts = Aircraft.price_over_1000
    else
      @aircrafts = Aircraft.all
    end
  end

  def new
    @aircraft = Aircraft.new
  end

  def show
  end

  def my_aircraft
    @aircrafts = Aircraft.where("user_id = ?", current_user.id)
  end

  def edit
  end

  def update
    @aircraft = Aircraft.find(params[:id])
    @aircraft.update(aircraft_params)
    redirect_to aircraft_path(@aircraft)
  end

  def destroy
    @aircraft.destroy
    redirect_to my_aircraft_aircrafts_path
  end

  def create
    @aircraft = Aircraft.new(aircraft_params)
    @aircraft.user = current_user
    if @aircraft.save
      redirect_to aircraft_path(@aircraft)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_aircraft
    @aircraft = Aircraft.find(params[:id])
  end

  def aircraft_params
    params.require(:aircraft).permit(
      :aircraft_type, :title, :description, :price_per_day,
      :price_0_to_500, :price_500_to_1000, :price_over_1000,
      :max_occupants, :departure_address, :arrival_address, photos: []
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_aircraft, only: %i[new create]

  def index
    @your_bookings = Booking.where("user_id = ?", current_user.id)
    @your_aircraft_bookings = Booking.joins(:aircraft).where(aircraft: { user_id: current_user.id })
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.aircraft = @aircraft
    number_of_days = (@booking.end_date - @booking.start_date) + 1
    @booking.total_price = @aircraft.price_per_day * number_of_days
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = Booking.find(params[:id])
    @aircraft = Aircraft.find(@booking.aircraft_id)

  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      number_of_days = (@booking.end_date - @booking.start_date) + 1
      aircraft = Aircraft.find(@booking.aircraft_id)
      @booking.update(total_price: (aircraft.price_per_day * number_of_days))
      redirect_to booking_path(@booking)
    else
      @aircraft = Aircraft.find(@booking.aircraft_id)
      render :edit, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(confirmation_status: true)
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(confirmation_status: false)
    redirect_to bookings_path
  end

  private

  def aircraft_params
    params.require(:aircraft).permit(
      :aircraft_type, :title, :description, :price_per_day,
      :max_occupants, :departure_address, :arrival_address, photos: []
    )
  end

  def booking_params
    params.require(:booking).permit(
      :start_date, :end_date, :aircraft_id, :user_id, :total_price, :confirmation_status, :confirm
    )
  end

  def set_aircraft
    @aircraft = Aircraft.find(params[:aircraft_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :sign_up]
  # Is Index here working?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_aircraft, only: %i[new create destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.aircraft = @aircraft
    @review.user = current_user
    if @review.save
      redirect_to aircraft_path(@aircraft)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    @aircraft = Aircraft.find(@review.aircraft_id)
    redirect_to aircraft_path(@aircraft)
  end

  def destroy
    @review.destroy
    redirect_to aircraft_path(@review.aircraft), status: :see_other
  end

  private

  def set_aircraft
    @aircraft = Aircraft.find(params[:aircraft_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aircrafts/edit.html.erb
<h2> Edit your <%= @aircraft.aircraft_type %></h2>

<%= render "shared/aircraft_form" %>

app/views/aircrafts/index.html.erb
<div class="container mt-5">
  <div class="row gy-5">
    <div class="col-12">
      <h1>Hire an Aircraft</h1>
      <br>
    </div>
  </div>

  <div class="row g-5 ">
    <% @aircrafts.each do |aircraft| %>
    <div class="col-3 card-deck ">
      <div class="card rounded-3 h-100 shadow">
        <% if aircraft.photos.attached? %>
        <%= cl_image_tag aircraft.photos[0].key,:gravity=>"auto", crop: :fill, :class=>"rounded-3" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= aircraft.aircraft_type %></h5>
          <p class="card-text">
            <p><b><span>Departure City:</span></b>
              <span><%= aircraft.departure_address %></span></p>
            <p><b><span>Arrival City:</span></b>
              <span><%= aircraft.arrival_address %></span></p>
            <p><b>Seats:</b> <%= aircraft.max_occupants %></p>
          </p>
        </div>
        <div class="card-footer bg-transparent border-0">
          <%= link_to "Book from $#{aircraft.price_per_day} per day", aircraft_path(aircraft), class: "btn btn-primary w-100" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/aircrafts/my_aircraft.html.erb
<div class="container mt-3">
  <div class="row">
      <h1 class="col-12">Your Aircraft</h1>
      <p><%= link_to "+ Add an Aircraft listing", new_aircraft_path, class: "btn btn-primary" %></p>
  </div>
  <div class="row g-5">
    <% @aircrafts.each do |aircraft| %>
    <div class="col-3 card-deck ">
      <div class="card rounded-3 h-100 shadow" >
        <% if aircraft.photos.attached? %>
            <%= cl_image_tag aircraft.photos[0].key,:gravity=>"auto", crop: :fill %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= aircraft.aircraft_type %></h5>
          <p class="card-text">
            <p><b><span><strong>Departure City:</strong></span></b>
            <span><%= aircraft.departure_address %></span></p>
            <p><b><span><strong>Arrival City:</strong></span></b>
            <span><%= aircraft.arrival_address %></span></p>
            <p><b><strong>Seats:</strong></b> <%= aircraft.max_occupants %></p>
            <p><b><strong>Price per day:</strong></b> $<%= aircraft.price_per_day %></p>
          </p>
        </div>
        <div class="card-footer bg-transparent border-0">
          <%= link_to "View", aircraft_path(aircraft), class: "btn btn-primary " %>
          <%= link_to "Edit", edit_aircraft_path(aircraft), class: "btn btn-secondary "  %>
          <%= link_to "Remove", aircraft_path(aircraft), class: "btn btn-danger text-white" ,data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/aircrafts/new.html.erb
<H2> Have a plane you want to rent out? List it on SkyHigh!</H2>

<%= render "shared/aircraft_form" %>

app/views/aircrafts/show.html.erb
<div class="container">
<h1 class="text-center"><%= @aircraft.title %></h1>
<div id="carouselExampleFade" class="carousel slide carousel-fade mb-3" data-bs-ride="carousel">
  <div class="carousel-inner">
      <% if @aircraft.photos.attached? %>
        <% @aircraft.photos.each do |photo| %>
        <div class="carousel-item active">
          <%= cl_image_tag photo.key, class:"d-block w-100", height:500 %>
        </div>
        <% end %>
      <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h2><%= @aircraft.aircraft_type %></h2>
<p><%= @aircraft.description %></p>
<p>Seats: <%= @aircraft.max_occupants %></p>
<p>Price per day: $<%= @aircraft.price_per_day %></p>
<p>Departure Address: <%= @aircraft.departure_address %></p>
<p>Arrival Address: <%= @aircraft.arrival_address %></p>
<div class="text-center"><%= link_to "Make a booking!",  new_aircraft_booking_path(@aircraft), class: "btn btn-primary w-50" %></div>
</div>


<p><strong>Reviews</strong></p>
 <% if @aircraft.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this aircraft</em></small>
      <% end %>
<ul class="list-group">
  <% @aircraft.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %>
    <div class="text-center"> <%= link_to "Edit your review", edit_aircraft_review_path(review), class: "btn btn-primary " %></li>
    </div>
  <% end %>

</ul>
<br>

app/views/bookings/edit.html.erb
<h2> Your Booking </h2>

<div class="text-center">
  <h1> Your Booking Details </h1>
</div>
<div class="container">
  <h2 class="text-center"><%= @aircraft.title %> from
  <br>
  <%= @booking.start_date.strftime('%d/%b/%Y') %> to <%= @booking.end_date.strftime('%d/%b/%Y') %></h1>
  <p><strong>Seats:</strong> <%= @aircraft.max_occupants %></p>
  <p><strong>Price per day:</strong> $<%= @aircraft.price_per_day %></p>
  <p><strong>Total Price:</strong> $<%= (@booking.end_date.mjd + 1 - @booking.start_date.mjd)*@aircraft.price_per_day %> </p>
  <p><strong>Departure Address:</strong> <%= @aircraft.departure_address %></p>
  <p><strong>Arrival Address:</strong> <%= @aircraft.arrival_address %></p>

  <%= simple_form_for [@booking], data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
    <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <div class="row gy-5">
    <div class="col-12">
      <h1>Your Bookings</h1>
    </div>
  </div>

<div class="row g-5 ">
    <% @your_bookings.order(:id).each do |your_booking| %>
    <div class="col-3 card-deck ">
      <div class="card rounded-3 h-100 shadow" >
        <div class="card-body">
          <h5 class="card-title">Booking ID # <%= your_booking.id %></h5>
          <p class="card-text">
          <% aircraft = Aircraft.find(your_booking.aircraft_id)%>
            <h6><%= aircraft.aircraft_type %></h6>
            <p><b><span>Departure City:</span></b>
            <span><%= aircraft.departure_address %></span></p>
            <p><b><span>Arrival City:</span></b>
            <span><%= aircraft.arrival_address %></span></p>
            <p><b>Seats:</b> <%= aircraft.max_occupants %></p>
            <p><b>Start Date:</b> <%= your_booking.start_date %></p>
            <p><b>End Date:</b> <%= your_booking.end_date %></p>
            <p><b>Booking Status:</b>
            <% case your_booking.confirmation_status %>
            <% when false %>
              <span>Declined</span>
            <% when true %>
              <span>Confirmed</span>
            <% else  %>
              <span>Pending</span>
            <% end %>
            </p>
        </div>
        <div class="card-footer bg-transparent border-0">
          <%= link_to "View", booking_path(your_booking), class: "btn btn-primary" %>
          <%= link_to "Edit", edit_booking_path(your_booking), class: "btn btn-secondary "  %>
          <%= link_to "Delete", booking_path(your_booking), class: "btn btn-danger text-white" ,data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>



<div class="container mt-5">
  <div class="row gy-5">
    <div class="col-12">
      <h1>Your Aircraft Bookings</h1>
    </div>
  </div>

 <div class="row g-5 ">
    <% @your_aircraft_bookings.order(:id).each do |your_aircraft_booking| %>
    <div class="col-3 card-deck ">
      <div class="card rounded-3 h-100 shadow" >
        <div class="card-body">
          <h5 class="card-title">Booking ID # <%= your_aircraft_booking.id %></h5>
          <p class="card-text">
          <% aircraft = Aircraft.find(your_aircraft_booking.aircraft_id)%>
            <h6><%= aircraft.aircraft_type %></h6>
            <p><b><span>Departure City:</span></b>
            <span><%= aircraft.departure_address %></span></p>
            <p><b><span>Arrival City:</span></b>
            <span><%= aircraft.arrival_address %></span></p>
            <p><b>Seats:</b> <%= aircraft.max_occupants %></p>
            <p><b>Start Date:</b> <%= your_aircraft_booking.start_date %></p>
            <p><b>End Date:</b> <%= your_aircraft_booking.end_date %></p>
            <p><b>Booking Status:</b>
            <% case your_aircraft_booking.confirmation_status %>
            <% when false %>
              <span>Declined</span>
            <% when true %>
              <span>Confirmed</span>
            <% else  %>
              <span>Pending</span>
            <% end %>
            </p>
          </p>
        </div>
        <div class="card-footer bg-transparent border-0">
          <%= link_to "Confirm", accept_booking_path(your_aircraft_booking), class: "btn btn-primary" %>
          <%= link_to "Decline", decline_booking_path(your_aircraft_booking), class: "btn btn-danger text-white"  %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Booking for <%= @aircraft.aircraft_type %>!</h1>
<p><strong>Seats</strong>: <%= @aircraft.max_occupants %></p>
<p><strong>Price per day</strong>: $<%= @aircraft.price_per_day %></p>
<p><strong>Departure Address:</strong> <%= @aircraft.departure_address %></p>
<p><strong>Arrival Address:</strong> <%= @aircraft.arrival_address %></p>
<div class="w-50">
<%= render "shared/booking_form" %>
</div>

app/views/bookings/show.html.erb
<div class="text-center">
  <h1> Your Booking Details </h1>
</div>

<% aircraft = Aircraft.find(@booking.aircraft_id) %>

<div class="container">
  <h2 class="text-center"><%= aircraft.title %> from
  <br>
  <%= @booking.start_date.strftime('%d/%b/%Y') %> to <%= @booking.end_date.strftime('%d/%b/%Y') %></h1>
  <p>Seats: <%= aircraft.max_occupants %></p>
  <p>Price per day: $<%= aircraft.price_per_day %></p>
  <p>Total Price: $<%= (@booking.end_date.mjd + 1 - @booking.start_date.mjd)*aircraft.price_per_day %> </p>
  <p>Departure Address: <%= aircraft.departure_address %></p>
  <p>Arrival Address: <%= aircraft.arrival_address %></p>
  <p>Booking Status:
            <% case @booking.confirmation_status %>
            <% when false %>
              <span>Declined</span>
            <% when true %>
              <span>Confirmed</span>
            <% else  %>
              <span>Pending</span>
            <% end %>
            </p>
  <div id="carouselExampleFade" class="carousel slide carousel-fade mb-3" data-bs-ride="carousel">
    <div class="carousel-inner">
        <% if aircraft.photos.attached? %>
          <% aircraft.photos.each do |photo| %>
          <div class="carousel-item active">
            <%= cl_image_tag photo.key, class:"d-block w-100", height:500 %>
          </div>
          <% end %>
        <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="text-center">
  <%= link_to "Read More About Your #{aircraft.aircraft_type}",aircraft_path(aircraft), class: "btn btn-primary " %>
  OR
  <%= link_to "Leave a Review after you Fly", new_aircraft_review_path(aircraft) ,class: "btn btn-primary " %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyHigh</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Plane_font_awesome.svg/2048px-Plane_font_awesome.svg.png" rel="icon" type="image/png" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mt-5">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h2> Your Review </h2>

<div class="container">
  <%= simple_form_for (@review) do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@aircraft, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_aircraft_form.erb
<%= simple_form_for(@aircraft) do |f| %>
  <%= f.input :aircraft_type %>
  <%= f.input :title %>
  <%= f.input  :description %>
  <%= f.input  :max_occupants %>
  <%= f.input  :price_per_day %>
  <%= f.input  :arrival_address %>
  <%= f.input  :departure_address %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/shared/_booking_form.erb
<%= simple_form_for [@aircraft, @booking], data: { controller: 'flatpickr' } do |f| %>
  <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container fluid">
<div class="container w-100 t-10">

  <div class="container w-75 t-10">
    <div class="navbar bg-light rounded-pill ps-5 pe-5">
      <div class="container-fluid">

        <a class="navbar-brand" href="/">
          <i class="fa-regular fa-paper-plane"></i>
          <b>FlyHigh</b>
        </a>

        <div>
          <%= form_with url: aircrafts_path, method: :get do %>
          <div class="input-group">
            <%= text_field_tag :query,
          params[:query],
          class: "form-control form-rounded",
          placeholder: "Let's get high"
        %>
            <span class="input-group-text form-rounded" id="basic-addon1"><i
                class="fa-regular fa-paper-plane"></i></span>
          </div>
          <% end %>
        </div>

        <div>
          <ul class="nav">
            <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Bookings", bookings_path , class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/53/53548.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <ul class="dropdown-menu dropdown-menu-end">
              </li>
              <%= link_to "My Aircraft", my_aircraft_aircrafts_path , class: "nav-link" %>
            </li>
                <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </ul>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

    </div>
    <% if controller.controller_name == 'aircrafts' && controller.action_name == 'index' %>
  <div class="d-flex justify-content-center">
          <div class="btn-group btn-group-sm mt-2">
            <%= link_to "$0-$500", { price_0_to_500: "1" }, class: "btn btn-outline-secondary form-rounded", data: { turbolinks: false } %>
            <%= link_to "$500-$1k", { price_500_to_1000: "1" }, class: "btn btn-outline-secondary", data: { turbolinks: false } %>
            <%= link_to "$1k+", { price_over_1000: "1" }, class: "btn btn-outline-secondary form-rounded", data: { turbolinks: false } %>
          </div>
          </div>
          <% end %>
  </div>
</div